name: Keep scheduled workflow activity

on:
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 UTC

jobs:
  keep-scheduled-workflow-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Keep scheduled workflow activity
        uses: WaterLemons2k/scheduled-workflow-activity-action@v1
